correct PyPI deployment

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -46,8 +46,9 @@ jobs:
         tox -e ${{ matrix.config[1] }}
 
   deploy-tag-to-pypi:
+    name: Publish Package on PyPI
     # only deploy on tags, see https://stackoverflow.com/a/58478262/1320237
-    if: startsWith(github.ref, 'refs/tags/v')
+    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     needs:
     - run-tests
     runs-on: ubuntu-latest
@@ -55,7 +56,7 @@ jobs:
     # see https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
     environment:
       name: PyPI
-      url: https://pypi.org/project/recurring-ical-events/
+      url: https://pypi.org/project/open-web-calendar/
     # after using the environment, we need to make the secrets available
     # see https://docs.github.com/en/actions/security-guides/encrypted-secrets#example-using-bash
     env:
@@ -66,27 +67,27 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
-        python-version: "3.9"
+        python-version: "3.12"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install --upgrade wheel twine build
-    - name: Check the tag
-      run: |
-        PACKAGE_VERSION=`python setup.py --version`
-        TAG_NAME=v$PACKAGE_VERSION
-        echo "Package version $PACKAGE_VERSION with possible tag name $TAG_NAME on $GITHUB_REF_NAME"
-        # test that the tag represents the version
-        # see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
-        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables
-        if [ "$TAG_NAME" != "$GITHUB_REF_NAME" ]; then
-          echo "ERROR: This tag is for the wrong version. Got \"$GITHUB_REF_NAME\" expected \"$TAG_NAME\"."
-          exit 1
-        fi
+#    - name: Check the tag
+#      run: |
+#        PACKAGE_VERSION=`python setup.py --version`
+#        TAG_NAME=v$PACKAGE_VERSION
+#        echo "Package version $PACKAGE_VERSION with possible tag name $TAG_NAME on $GITHUB_REF_NAME"
+#        # test that the tag represents the version
+#        # see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
+#        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables
+#        if [ "$TAG_NAME" != "$GITHUB_REF_NAME" ]; then
+#          echo "ERROR: This tag is for the wrong version. Got \"$GITHUB_REF_NAME\" expected \"$TAG_NAME\"."
+#          exit 1
+#        fi
     - name: remove old files
       run: rm -rf dist/*
     - name: build distribution files
-      run: python setup.py bdist_wheel sdist
+      run: python -m build
     - name: deploy to pypi
       run: |
         # You will have to set the variables TWINE_USERNAME and TWINE_PASSWORD
@@ -105,21 +106,21 @@ jobs:
         fi
         twine check dist/*
         twine upload dist/*
-
-  deploy-github-release:
+          
+  github-release:
+    name: "Publish GitHub Release"
     # only deploy on tags, see https://stackoverflow.com/a/58478262/1320237
-    if: startsWith(github.ref, 'refs/tags/v')
+    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     needs:
-    - run-tests
-    - deploy-tag-to-pypi
+      - run-tests
+      - dockerhub
+      - deploy-tag-to-pypi
     runs-on: ubuntu-latest
-    environment:
-      name: github-release
     steps:
       - uses: actions/checkout@v4
-      - name: Create GitHub release from tag
+      - name: create release
         uses: ncipollo/release-action@v1
         with:
           allowUpdates: true
-          body: "To view the changes, please see the [Changelog](https://github.com/niccokunzmann/python-recurring-ical-events?tab=readme-ov-file#changelog). This release can be installed from [PyPI](https://pypi.org/project/recurring-ical-events/#history)."
+          body: "For a list of changes, please refer to the [Changelog](https://open-web-calendar.quelltext.eu/changelog/)."
           generateReleaseNotes: false
